### ISSUE TITLE
历史数据的获取方式

### ISSUE THREAD

**Issue by Timmy-Fang** [paulhybryant/convertible_bond#3]
你好，谢谢你的分享，请问转债的历史数据的获取是从哪里获得的呢？我知道集思录上没有可导出的历史数据。你所说的量化回测平台上有详细完整的历史数据吗？比如聚宽与米筐之类的。谢谢

**Comment by paulhybryant** [comment]
聚宽有可转债的历史数据。代码里的jqdatasdk就是聚宽的data API。
但是聚宽的问题是现在不支持转债的回测（写完了代码以后才发现。。。）
其他的平台也有（米筐，掘金，优矿，Bigquant等等）
