### ISSUE TITLE
能提供个简单的使用手册吗

### ISSUE THREAD

**Issue by sxf5487** [paulhybryant/convertible_bond#4]
大神，您好，首先感谢你今天百忙之中更新代码，请问能提供个简单的使用手册吗？
更新前我配置了auth.json文件后能运行，但是更新后我不知道如何使用了，非常感谢！

**Comment by sxf5487** [comment]
自己摸索了下，还是报如下错误。
<img width="870" alt="image" src="https://user-images.githubusercontent.com/50735006/133771645-3ef957b8-0ea8-4fec-97d8-2f4f58979a7f.png">

**Comment by paulhybryant** [comment]
已经修复。
如果你只是需要生成标的，看现在打印出来的东西就可以了。positions主要是记录之前的操作。

**Comment by sxf5487** [comment]
<img width="850" alt="image" src="https://user-images.githubusercontent.com/50735006/134768492-ee4d1ed6-5171-4b38-909d-96f2dcc680fa.png">
git pull后直接报错了。

**Comment by paulhybryant** [comment]
聚宽的数据源现在并没有维护。要么用集思录的，要么用米筐的（rqdata）
